version: "3.9"

services:
  db:
    image: postgres:15
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - bot-network

  pgadmin:
    image: dpage/pgadmin4:latest
    env_file:
      - .env
    ports:
      - "8080:80"
    volumes:
      - pgadmin_sessions:/var/lib/pgadmin
      - pgadmin_data:/pgadmin
    depends_on:
      - db
    networks:
      - bot-network

  bot:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
     - .env
    depends_on:
     - db
    networks:
     - bot-network

volumes:
  postgres_data:
  pgadmin_data:
  pgadmin_sessions:

networks:
  bot-network:
    driver: bridge
